### ISSUE TITLE
Prepopulate Hotspots

### ISSUE THREAD

**Issue by danatimmediate** [cn-wx/vue-hotspot#60]
Hi - is there a way to prepopulate hotspots?

**Comment by cn-wx** [comment]
@danatimmediate Hi, I am working on this feature(bug), will publish a new version and document it after unit testing

**Comment by danatimmediate** [comment]
@cn-wx Excellent - thank you 👍

**Comment by cn-wx** [comment]
@danatimmediate Hi, please upgrade the version to `1.1.7+` and see [readme](https://github.com/cn-wx/vue-hotspot#config-options) for detailed usage, thank you.

**Comment by danatimmediate** [comment]
That's amazing James. I wasn't expecting for you to do it straight away or anything! Thank you very much, works really well! 🥇
